### ISSUE TITLE
NullPointerException when coming back from Add savings account page.

### ISSUE THREAD

**Issue by Sreedev** [openMF/android-client#190]
- Click a client from client list.
- From toolbar select Add Savings Account.
- Without entering any data just press back button.
Sometimes app crashed, sometimes not.

03-09 12:06:27.364  22635-22635/com.mifos.mifosxdroid E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.mifos.mifosxdroid, PID: 22635
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
            at android.view.LayoutInflater.from(LayoutInflater.java:229)
            at android.widget.ArrayAdapter.<init>(ArrayAdapter.java:178)
            at android.widget.ArrayAdapter.<init>(ArrayAdapter.java:163)
            at com.mifos.mifosxdroid.online.SavingsAccountFragment$6.success(SavingsAccountFragment.java:486)
            at com.mifos.mifosxdroid.online.SavingsAccountFragment$6.success(SavingsAccountFragment.java:444)
            at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by Sreedev** [comment]
I am working on this.

**Comment by RowlandOti** [comment]
@Sreedev , have you solved this?

**Comment by Sreedev** [comment]
@RowlandOti  No, You can take this forward.

**Comment by Sreedev** [comment]
@RowlandOti  Sorry for late reply. I am out of station, you can work on this.

**Comment by xiprox** [comment]
I think I see what the issue here is. The Fragment is probably no longer attached to an Activity by the time the `success` method is executed. This causes `null` to be passed to the `ArrayAdapter` which in turn causes the `java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference` exception to be thrown. I'll look into it if it's ok.

**Comment by RowlandOti** [comment]
I don't know why,  but I can't just be able to reproduce this issue!

**Comment by xiprox** [comment]
Hmm. I haven't tried to reproduce it myself yet.

Do you have a fast connection? It could be that the crash happens on slow connections. If we assume that the following happens: `API request is sent` —> `user exits Fragment` —> `Fragment is detached` —> `success is called` —> `Crash`, we could say that you should be able to reproduce the crash if you can exit the fragment before the request completes.

**Comment by RowlandOti** [comment]
@xiprox , yes my internet is quite fast. I will try to throttle it and see what happens.

**Comment by xiprox** [comment]
Ok, I got to reproduce the crash by:
1. Tapping `Add Savings Account`.
2. Tapping back button repeatedly.
