### ISSUE TITLE
NPE when navigating back from SavingsAccountSummaryFragment

### ISSUE THREAD

**Issue by xiprox** [openMF/android-client#253]
```
E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.mifos.mifosxdroid, PID: 8038
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
    at android.view.LayoutInflater.from(LayoutInflater.java:229)
    at com.mifos.mifosxdroid.adapters.SavingsAccountTransactionsListAdapter.<init>(SavingsAccountTransactionsListAdapter.java:35)
    at com.mifos.mifosxdroid.online.SavingsAccountSummaryFragment$1.success(SavingsAccountSummaryFragment.java:186)
    at com.mifos.mifosxdroid.online.SavingsAccountSummaryFragment$1.success(SavingsAccountSummaryFragment.java:153)
    at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Same thing as #190. Same changes should fix this too. If anyone is up, please do it. Otherwise I'll take a look at it once I'm done with [MIFOSAC-139](https://mifosforge.jira.com/browse/MIFOSAC-139).

**UPDATE:** Realized that this crash does not happen with the current code since ProgressDialogs are blocking user interaction (i.e., navigating back). It only happens because [MIFOSAC-139](https://mifosforge.jira.com/browse/MIFOSAC-139) allows users to leave the fragment before network operations complete. I'll be fixing these crashes as the second stage of  [MIFOSAC-139](https://mifosforge.jira.com/browse/MIFOSAC-139).

**Comment by mayank-kgp** [comment]
@xiprox  Please give an update on this issue. 
Is it resolved?

**Comment by xiprox** [comment]
Oh. I'm sorry. Somehow forgot to close this I guess. Yes, it's been fixed with https://github.com/openMF/android-client/pull/255/commits/3abacafd709d95aff68da659aad8e2610305a314
