### ISSUE TITLE
Document upload is failing 

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/android-client#289]
Failed to upload Documents 

```java
06-12 11:25:30.075 7842-7842/com.mifos.mifosxdroid E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.mifos.mifosxdroid, PID: 7842
                                                                     java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=196608, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:2389 flg=0x43 }} to activity {com.mifos.mifosxdroid/com.mifos.mifosxdroid.online.ClientActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
                                                                         at android.app.ActivityThread.deliverResults(ActivityThread.java:3720)
                                                                         at android.app.ActivityThread.handleSendResult(ActivityThread.java:3763)
                                                                         at android.app.ActivityThread.-wrap16(ActivityThread.java)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                      Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
                                                                         at java.io.File.fixSlashes(File.java:183)
                                                                         at java.io.File.<init>(File.java:130)
                                                                         at com.mifos.mifosxdroid.dialogfragments.documentdialog.DocumentDialogFragment.onActivityResult(DocumentDialogFragment.java:159)
                                                                         at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:156)
                                                                         at android.app.Activity.dispatchActivityResult(Activity.java:6470)
                                                                         at android.app.ActivityThread.deliverResults(ActivityThread.java:3716)
                                                                         at android.app.ActivityThread.handleSendResult(ActivityThread.java:3763) 
                                                                         at android.app.ActivityThread.-wrap16(ActivityThread.java) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:148) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
```

**Comment by therajanmaurya** [comment]
fix #336
