### ISSUE TITLE
Rx onError crashed During Syncing Client Offline

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/android-client#309]
```java
07-21 19:02:32.625 31956-1060/com.mifos.mifosxdroid D/OkHttp: --> POST https://demo.openmf.org/fineract-provider/api/v1/clients http/1.1
07-21 19:02:32.626 31956-1060/com.mifos.mifosxdroid D/OkHttp: Content-Type: application/json; charset=UTF-8
07-21 19:02:32.626 31956-1060/com.mifos.mifosxdroid D/OkHttp: Content-Length: 306
07-21 19:02:32.626 31956-1060/com.mifos.mifosxdroid D/OkHttp: {"activationDate":"21 Jul 2016","active":true,"clientClassificationId":34,"clientTypeId":101,"dateFormat":"dd MMMM YYYY","dateOfBirth":"21 Jul 2016","externalId":"2525","firstname":"gabha","genderId":22,"lastname":"avaha","locale":"en","middlename":"agaha","mobileNo":"9464879648","officeId":1,"staffId":1}
07-21 19:02:32.626 31956-1060/com.mifos.mifosxdroid D/OkHttp: --> END POST (306-byte body)
07-21 19:02:33.362 31956-1060/com.mifos.mifosxdroid D/OkHttp: <-- 403 Forbidden https://demo.openmf.org/fineract-provider/api/v1/clients (735ms)
07-21 19:02:33.362 31956-1060/com.mifos.mifosxdroid D/OkHttp: Server: Apache-Coyote/1.1
07-21 19:02:33.362 31956-1060/com.mifos.mifosxdroid D/OkHttp: Access-Control-Allow-Origin: *
07-21 19:02:33.362 31956-1060/com.mifos.mifosxdroid D/OkHttp: Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
07-21 19:02:33.362 31956-1060/com.mifos.mifosxdroid D/OkHttp: Content-Type: application/json
07-21 19:02:33.362 31956-1060/com.mifos.mifosxdroid D/OkHttp: Transfer-Encoding: chunked
07-21 19:02:33.362 31956-1060/com.mifos.mifosxdroid D/OkHttp: Vary: Accept-Encoding
07-21 19:02:33.362 31956-1060/com.mifos.mifosxdroid D/OkHttp: Date: Thu, 21 Jul 2016 13:33:11 GMT
07-21 19:02:33.363 31956-1060/com.mifos.mifosxdroid D/OkHttp: {"developerMessage":"The request caused a data integrity issue to be fired by the database.","httpStatusCode":"403","defaultUserMessage":"Client with externalId `2525` already exists","userMessageGlobalisationCode":"error.msg.client.duplicate.externalId","errors":[{"developerMessage":"Client with externalId `2525` already exists","defaultUserMessage":"Client with externalId `2525` already exists","userMessageGlobalisationCode":"error.msg.client.duplicate.externalId","parameterName":"externalId","value":null,"args":[{"value":"2525"}]}]}
07-21 19:02:33.363 31956-1060/com.mifos.mifosxdroid D/OkHttp: <-- END HTTP (541-byte body)
07-21 19:02:33.464 31956-31956/com.mifos.mifosxdroid E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.mifos.mifosxdroid, PID: 31956
                                                                       java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                                           at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
                                                                           at android.os.Handler.handleCallback(Handler.java:746)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                        Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
                                                                           at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:192)
                                                                           at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
                                                                           at rx.internal.operators.OperatorSubscribeOn$1$1.onError(OperatorSubscribeOn.java:59)
                                                                           at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:264)
                                                                           at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:207)
                                                                           at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                           at android.os.Handler.handleCallback(Handler.java:746) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                           at android.os.Looper.loop(Looper.java:148) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
                                                                        Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
                                                                           at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:192) 
                                                                           at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120) 
                                                                           at rx.internal.operators.OperatorSubscribeOn$1$1.onError(OperatorSubscribeOn.java:59) 
                                                                           at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:264) 
                                                                           at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:207) 
                                                                           at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
                                                                           at android.os.Handler.handleCallback(Handler.java:746) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                           at android.os.Looper.loop(Looper.java:148) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
                                                                        Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
                                                                           at com.crashlytics.android.v.a(SourceFile:1811)
                                                                           at com.crashlytics.android.v.a(SourceFile:1814)
                                                                           at com.crashlytics.android.v.a(SourceFile:1814)
                                                                           at com.crashlytics.android.v.b(SourceFile:1753)
                                                                           at com.crashlytics.android.v.a(SourceFile:1714)
                                                                           at com.crashlytics.android.v.a(SourceFile:1457)
                                                                           at com.crashlytics.android.v.a(SourceFile:66)
                                                                           at com.crashlytics.android.N.call(SourceFile:307)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                           at com.crashlytics.android.internal.am.a(SourceFile:44)
                                                                           at com.crashlytics.android.internal.aa.run(SourceFile:13)
                                                                           at java.lang.Thread.run(Thread.java:818)
                                                                        Caused by: retrofit2.adapter.rxjava.HttpException: HTTP 403 Forbidden
                                                                           at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$SimpleCallAdapter$1.call(RxJavaCallAdapterFactory.java:204)
                                                                           at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$SimpleCallAdapter$1.call(RxJavaCallAdapterFactory.java:199)
                                                                           at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:66)
                                                                           at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:146)
                                                                           at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:125)
                                                                           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
                                                                           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
                                                                           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                           at rx.Observable.unsafeSubscribe(Observable.java:8452)
                                                                           at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:94)
                                                                           at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:42)
                                                                           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
                                                                           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                           at rx.Observable.unsafeSubscribe(Observable.java:8452)
                                                                           at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                                                                           at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:222)
                                                                           at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                           at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecu
```

**Comment by therajanmaurya** [comment]
Fix #310
