### ISSUE TITLE
App crashing on scrolling through path tracker 

### ISSUE THREAD

**Issue by aj019** [openMF/android-client#542]
**Summary:** 

The app crashes when the Path tracker fragment is loaded and the list is scrolled.

**Steps to reproduce:** 

1) Go to path tracker
2) Scroll through the list 

**Expected behavior:** 

Normally we should be able to scroll seamlessly through the list.

**Observed behavior:** 

The app crashes as we scrolll through the list. 

**Device and Android version:** 

Google Nexus 4 Android 4.4 API 19

**Screenshots:** 

<img width="417" alt="screen shot 2017-02-25 at 12 01 22 am" src="https://cloud.githubusercontent.com/assets/7893859/23316001/b4a41a24-faee-11e6-9411-fff3e2ccf14b.png">

**Stack Trace**

`02-24 12:56:18.539 2233-2233/com.mifos.mifosxdroid E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.mifos.mifosxdroid, PID: 2233
                                                                     java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                                         at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                         at java.util.ArrayList.get(ArrayList.java:308)
                                                                         at com.mifos.mifosxdroid.adapters.PathTrackingAdapter.onBindViewHolder(PathTrackingAdapter.java:63)
                                                                         at com.mifos.mifosxdroid.adapters.PathTrackingAdapter.onBindViewHolder(PathTrackingAdapter.java:36)
                                                                         at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5217)
`

**Comment by therajanmaurya** [comment]
@aj019  You can on the latest build. Please pull master branch and build and run again. It's working fine.

**Comment by therajanmaurya** [comment]
I have checked the fabric there is no crash report It means you are working on old build please update and please install the Google Play Services before working.

I am closing this issue for now.
